apiVersion: v1
kind: Service
metadata:
  name: nodegateway
  labels:
    app: nodegateway
spec:
  selector:
    app: nodegateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegateway
  labels:
    app: nodegateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodegateway
  template:
    metadata:
      labels:
        app: nodegateway
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodegateway"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: nodegateway
        image: dapr-nodegateway:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
