apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp2
  labels:
    app: node2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node2
  template:
    metadata:
      labels:
        app: node2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp2"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node
        image: hello-node2:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
