apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp1
  labels:
    app: nodeapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp1
  template:
    metadata:
      labels:
        app: nodeapp1
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp1"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: nodeapp1
        image: dapr-node1:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
